version: '3.8'

services:
  # Buzz Admin App - Port 8081
  buzz-admin:
    build:
      context: .
      dockerfile: apps/buzz-admin/Dockerfile
      args:
        BUILD_ENV: development
    container_name: buzz-admin
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=development
    networks:
      - buzz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Buzz Business App - Port 8082  
  buzz-biz:
    build:
      context: .
      dockerfile: apps/buzz-biz/Dockerfile
      args:
        BUILD_ENV: development
    container_name: buzz-biz
    ports:
      - "8082:80"
    environment:
      - NODE_ENV=development
    networks:
      - buzz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Buzz Customer App - Port 8080
  buzz:
    build:
      context: .
      dockerfile: apps/buzz/Dockerfile
      args:
        BUILD_ENV: development
    container_name: buzz-app
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=development
    networks:
      - buzz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  buzz-network:
    driver: bridge